on:
  push:
    branches:
      - main
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read VERSION_NUMBER file
        id: version
        run: echo "::set-output name=version::$(cat VERSION_NUMBER)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          body: |
            minor changes in this Release.
          draft: false
          prerelease: false
